# Generated by Django 3.0.5 on 2021-03-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
