# Generated by Django 3.0.5 on 2021-03-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.TextField()),
                ('brand_slug', models.SlugField(help_text='Unique value for the product created from brand_name', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('product_slug', models.SlugField(help_text='Unique value for products, created from the products name', max_length=255, unique=True)),
                ('product_description', models.CharField(max_length=100)),
                ('meta_keywords', models.CharField(help_text='Content for the meta keywords', max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(help_text='Content for the Meta description', max_length=255, verbose_name='Meta description')),
                ('sku', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('product_image_one', models.ImageField(blank=True, height_field='image_height', help_text='The first image for the prouct', upload_to='imagefiles')),
                ('product_image_two', models.ImageField(blank=True, height_field='image_height', help_text='Another image for the product', upload_to='imagefiles')),
                ('product_image_three', models.ImageField(blank=True, height_field='image_height', help_text='another image for the product', upload_to='imagefiles')),
                ('image_height', models.PositiveIntegerField(default=100)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Brand')),
                ('category', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Categories.Category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
