# Generated by Django 2.0.13 on 2021-02-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.TextField()),
                ('slug', models.SlugField(help_text='Unique value for the product created from brand_name', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('slug', models.SlugField(help_text='Unique value for products, created from the products name', max_length=255, unique=True)),
                ('product_description', models.CharField(max_length=100)),
                ('meta_keywords', models.CharField(help_text='Content for the meta keywords', max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(help_text='Content for the Meta description', max_length=255, verbose_name='Meta description')),
                ('sku', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('product_image', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Brand')),
                ('categories', models.ManyToManyField(to='Categories.Category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
