# Generated by Django 3.0.5 on 2021-03-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_height',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_one',
            field=models.ImageField(blank=True, height_field='image_height', help_text='The first image for the prouct', upload_to='imagefiles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_three',
            field=models.ImageField(blank=True, height_field='image_field', help_text='another image for the product', upload_to='imagefiles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_two',
            field=models.ImageField(blank=True, height_field='image_height', help_text='Another image for the product', upload_to='imagefiles'),
        ),
    ]
