# Generated by Django 3.0.5 on 2021-03-11 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_height',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Categories.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_one',
            field=models.ImageField(blank=True, help_text='The first image for the prouct', upload_to='imagefiles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_three',
            field=models.ImageField(blank=True, help_text='another image for the product', upload_to='imagefiles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_two',
            field=models.ImageField(blank=True, help_text='Another image for the product', upload_to='imagefiles'),
        ),
    ]
