# Generated by Django 3.0.5 on 2021-03-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210309_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_three',
            field=models.ImageField(blank=True, height_field='image_height', help_text='another image for the product', upload_to='imagefiles'),
        ),
    ]
