# Generated by Django 2.0.13 on 2021-03-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210224_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_one',
            field=models.FileField(blank=True, help_text='The first image for the prouct', upload_to='imagefiles'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_three',
            field=models.FileField(blank=True, help_text='another image for the product', upload_to='imagefiles'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_two',
            field=models.FileField(blank=True, help_text='Another image for the product', upload_to='imagefiles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
