# Generated by Django 2.2.14 on 2021-03-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210311_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
