# Generated by Django 2.0.13 on 2021-03-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210301_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='slug',
            new_name='brand_slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='product_slug',
        ),
    ]
